version: "3.7"

services:
  app:
    build: .
    ports:
      - "8061:8061"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: gerald
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: telusko
    ports:
      - "5433:5432"